package vn.sapo.domain.purchaseorder.event;

public enum PurchaseOrderEventName {
    FIELD_VALUE_CHANGED,
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_CANCELLED,
    PURCHASE_ORDER_CONFIRMED,
    PURCHASE_ORDER_REJECTED,
    PURCHASE_ORDER_COMPLETED,
    PURCHASE_ORDER_DELIVERING,
    PURCHASE_ORDER_DELETED,

    PURCHASE_ORDER_LINE_ITEM_ADDED,
    PURCHASE_ORDER_LINE_ITEM_UPDATED,
    PURCHASE_ORDER_LINE_ITEM_REMOVED,
}
